/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Test2Import } from './routes/test2'
import { Route as TestImport } from './routes/test'
import { Route as AboutImport } from './routes/about'

// Create Virtual Routes

const ReactLazyImport = createFileRoute('/React')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReactLazyRoute = ReactLazyImport.update({
  id: '/React',
  path: '/React',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/React.lazy').then((d) => d.Route))

const Test2Route = Test2Import.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/test2': {
      id: '/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof Test2Import
      parentRoute: typeof rootRoute
    }
    '/React': {
      id: '/React'
      path: '/React'
      fullPath: '/React'
      preLoaderRoute: typeof ReactLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/React': typeof ReactLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/React': typeof ReactLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/React': typeof ReactLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/test' | '/test2' | '/React'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/test' | '/test2' | '/React'
  id: '__root__' | '/' | '/about' | '/test' | '/test2' | '/React'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRoute: typeof AboutRoute
  TestRoute: typeof TestRoute
  Test2Route: typeof Test2Route
  ReactLazyRoute: typeof ReactLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
  Test2Route: Test2Route,
  ReactLazyRoute: ReactLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/test",
        "/test2",
        "/React"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/test2": {
      "filePath": "test2.tsx"
    },
    "/React": {
      "filePath": "React.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
